### Environment constants 

LGW_PATH ?= ../../lora_gateway/libloragw
ARCH ?=
CROSS_COMPILE ?=
export

### general build targets

all:
	$(MAKE) all -e -C rtlora_gw

clean:
	$(MAKE) clean -e -C rtlora_gw

### EOF
